apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users-service
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: users-service
  type: NodePort
